name: 'first_pipeline'


on: 
  workflow_dispatch: 
  push: 
    branches: 
      - 'main'


jobs: 
  tester: 
    runs-on: 'ubuntu-latest'
    steps: 

      - name: 'checkout_repo_code'
        uses: actions/checkout@v6

      - name: 'test step 1'
        run: ls -la

      - name: 'test step 2'
        run: |
          cat README.md
          pwd
          ls -la
          cd ..
          ls -la /usr/local/bin
          whoami

  doris: 
    runs-on: 'ubuntu-latest'
    steps: 

      - name: 'python install'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 

      - name: 'python step 1'
        run: python --version

